version: '3'
services:
  # cf.: https://docs.docker.com/registry/deploying/
  registry:
    image: registry:2.6.1
    ports:
      - "5000:5000"
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/certs:/certs
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  # cf.: https://github.com/kwk/docker-registry-frontend/tree/v2
  ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "80:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
      ENV_DOCKER_REGISTRY_USE_SSL: 1
      #ENV_REGISTRY_PROXY_FQDN: ${HOSTNAME}
    links:
      - registry
    logging:
      <<: *logging
